language: node_js
sudo: required
node_js: 10.16.0
services:
- docker
- mongodb
before_deploy:
- npm install
- npm run build
- npm run test
deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: H2jXKktp2inr8JAi4qQOHramv3711jBjwfGFSVQyJs5KzgJYAqtoXEnvEv6l4AGoUk95v39/8xrqSa7SMhJVHAETGMKK0HJYBNyawPG6tiYy1H8fIoNMg4a8bLz7j2ZkEPHZqsoySHODcw2cW+cvS8ALNpr3YyojjsmyPuV0x2+qNdcO7NPBzAFXATdNn8UcVtFTZwL+snlNenPtDzE5hKwV8wHWj4NDc07s86cBO1zUIIXgA2FU5ZrUlNxQx3OUg9BOeY+VDXwKhTKQgSISIX0jPcWMM3+XC44Sv5Faq4trSJZfxXv0zidXmrzkOJGXR+XmAVOjPbYOaTUFIxg360fPM7/fkqh9dPlvaJgu2NaZeMeGjaKNjcJYSrqDbg5ifikasHqNeUFX3Je3UOe71QAiQ7MpFpBA/bpCRTzRTG2Wd2o1yG46TnX88GKebWwWh7ZBRRk4CFlLl5691wsQD3BvbtCMsEr/oCGZvUjhBr1NXxAOZOYtvERsJvrPC+8dpczl9ZNb1IaJe+VerpZ/e0mFZjneYuamq8AeWGVSReT3OgjYdZVl756IUAeMWNh5GUNu/SUizPcpvJtGL/BeUVonIOe5EIjLArcwm/93F2W0Z8/mJFcTRro6JnkJBuPi36HPq6z0X4WPnSIOqIkYrXR2QkSIRBSRQ4i08PtPFpw=
  app: adsk-bucharest
  on:
    repo: stancu-mihai/ADSKBucharest
    branch: master
