version: '2.2'
services:
  database:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "3000:3000"
    links:
      - database
    environment:
      PORT: 3000 # this is optional, allows express to use process.env.PORT instead of a raw 3000,
      MONGODB_URI: "mongodb://database:27017"
      MONGODB_URI_LOCAL: "mongodb://database:27017"